### ISSUE TITLE
Try using a scaling value in combination with calc()

### ISSUE THREAD

**Issue by rijkvanzanten** [dandevri/minor-cssttr#20]
F.e. this 
```css
:root {
  --margin-none: 0;
  --margin-small: 1em;
  --margin-medium: 2em;
  --margin-big: 3em;
}

el {
  margin: --margin-medium;
}
```
could be rewritten as
```css
:root {
  --scale: 1;
}

el {
  margin: calc(2em * --scale);
}
```

That way, when editing the scale, you don't have to edit each version of the variable
